dataset:
  class: datasets.IMDBDataset
  batch_size: 500

model:
  name: IMDBLSTM
  class: imdb.SimpleLSTM

  optimizer:
    class: AdamOptimizer
    learning_rate: 0.001

  inputs: [x, y]
  outputs: [accuracy, predictions, loss]
  session_config: {allow_soft_placement: True}

main_loop:
  extra_streams: [test]

hooks:
- ComputeStats:
    variables:
      loss: [mean]
      accuracy: [mean]
- LogVariables
- CatchSigint
- cxflow_tensorflow.hooks.WriteTensorboard