dataset:
  class: datasets.IMDBDataset
  batch_size: 500

model:
  name: IMDB_GRU
  class: imdb.SimpleGRU
  n_gpus: 1

  optimizer:
    class: AdamOptimizer
    learning_rate: 0.001

  inputs: [x, y]
  outputs: [accuracy, predictions, loss]
  session_config: {allow_soft_placement: True}

main_loop:
  extra_streams: [test]

hooks:
  - ComputeStats:
      variables:
        - loss: [mean, std]
        - accuracy
  - LogVariables
  - CatchSigint
  - SaveBest:
      stream: test
  - LogProfile
  - cxflow_tensorflow.hooks.WriteTensorBoard
  - StopAfter:
      epochs: 10

predict:
  model:
    inputs: [x]
    outputs: [predictions]
  hooks:
    - imdb.IMDBPredict
