dataset:
  class: cifar100.CIFARDataset
  batch_size: 128
  augment:
    horizontal_flip: True

model:
  name: WideResNet
  class: cifar100.wide_resnet.WideResNet
  depth: 28
  k: 10
  dropout: 0.3

  optimizer:
    class: MomentumOptimizer
    learning_rate: 0.01
    momentum: 0.9
    use_nesterov: True

  inputs: [images, labels]
  outputs: [accuracy, predictions, loss]

main_loop:
  extra_streams: [test]

hooks:
  - cxflow_tensorflow.hooks.DecayLR:
      decay_value: 0.98
      variable_name: learning_rate
      decay_type: multiply
  - ComputeStats:
      variables: [loss, accuracy]
  - LogVariables
  - SaveBest:
      stream: test
  - StopAfter:
      epochs: 200
